import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '@mantine/core/styles.css';
import { MantineProvider } from '@mantine/core';
import { HeaderTabs } from '@/components/header/HeaderTabs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider><HeaderTabs /></MantineProvider>
        <main className="flex min-h-screen flex-col justify-center  p-24">
          <MantineProvider>{children}</MantineProvider>
        </main>
      </body>
    </html>
  );
}
