name: Close Issue in Main Repo

on:
  pull_request:
    types: [closed]

jobs:
  close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch pull request comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: comments
      run: |
        COMMENTS_URL=$(jq -r '.pull_request.comments_url' "$GITHUB_EVENT_PATH")
        curl -H "Authorization: token $GITHUB_TOKEN" $COMMENTS_URL > comments.json

    - name: Extract issue number from comments
      id: extract_issue
      run: |
        ISSUE_NUMBER=$(jq -r '.[] | select(.body | test("Fixes #\\d+")) | .body' comments.json | grep -oP '(?<=close #)\d+')
        echo "::set-output name=issue_number::$ISSUE_NUMBER"

    - name: Close related issue in main repo
      if: steps.extract_issue.outputs.issue_number != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ steps.extract_issue.outputs.issue_number }}
      run: |
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/reckyy/tsundoku/issues/$ISSUE_NUMBER \
          -d '{"state": "closed"}'
