name: Close Issue in Main Repo

on:
  pull_request:
    types: [closed]

jobs:
  close-issue:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate GitHub Apps token
      id: generate
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Fetch pull request comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: comments
      run: |
        COMMENTS_URL=$(jq -r '.pull_request.comments_url' "$GITHUB_EVENT_PATH")
        curl -H "Authorization: token $GITHUB_TOKEN" $COMMENTS_URL > comments.json

    - name: Extract issue number from comments
      id: extract_issue
      run: |
        ISSUE_NUMBER=$(jq -r '.[] | select(.body | test("close #\\d+")) | .body' comments.json | grep -oP '(?<=close #)\d+')
        echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_ENV

    - name: Add PR URL comment to issue
      if: env.issue_number != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ env.issue_number }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: |
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/reckyy/tsundoku/issues/$ISSUE_NUMBER/comments \
          -d "{\"body\": \"[PRのURL]($PR_URL)\"}"

    - name: Close related issue in main repo
      if: env.issue_number != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ env.issue_number }}
      run: |
        curl -X PATCH \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/reckyy/tsundoku/issues/$ISSUE_NUMBER \
          -d '{"state": "closed"}'
